"""Add dob column to user table

Revision ID: 670088ab020f
Revises: 
Create Date: 2024-03-06 17:02:45.545611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '670088ab020f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dob', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('phonenum', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('phonenum')
        batch_op.drop_column('dob')

    # ### end Alembic commands ###
